### ISSUE TITLE
`WorldCreator.hardcore` doesn't exist on older servers

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomWorlds#35]
reported by khanh on discord

```
[19:40:39 ERROR]: Error occurred while enabling PhantomWorlds v2.0.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.WorldCreator.hardcore(Z)Lorg/bukkit/WorldCreator;
    at me.lokka30.phantomworlds.managers.WorldManager$PhantomWorld.create(WorldManager.java:168) ~[?:?]
    at me.lokka30.phantomworlds.managers.WorldManager.loadManagedWorlds(WorldManager.java:62) ~[?:?]
    at me.lokka30.phantomworlds.PhantomWorlds.loadWorlds(PhantomWorlds.java:159) ~[?:?]
    at me.lokka30.phantomworlds.PhantomWorlds.onEnable(PhantomWorlds.java:90) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
```

**Comment by lokka30** [comment]
should be fixed in upcoming version
