### ISSUE TITLE
`/pw setspawn` doesn't work on older servers

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomWorlds#36]
NoSuchMethodError.

Trimmed stack trace:
```
[15:01:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pw' in plugin PhantomWorlds v2.0.2
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.setSpawnLocation(Lorg/bukkit/Location;)Z
        at me.lokka30.phantomworlds.commands.phantomworlds.subcommands.SetSpawnSubcommand.parseCommand(SetSpawnSubcommand.java:168) ~[?:?]
```

Original stack trace:
```
[15:01:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pw' in plugin PhantomWorlds v2.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1341) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1151) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:6) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_311]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:782) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:413) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:721) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:624) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.setSpawnLocation(Lorg/bukkit/Location;)Z
        at me.lokka30.phantomworlds.commands.phantomworlds.subcommands.SetSpawnSubcommand.parseCommand(SetSpawnSubcommand.java:168) ~[?:?]
        at me.lokka30.phantomworlds.commands.phantomworlds.PhantomWorldsCommand.onCommand(PhantomWorldsCommand.java:72) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        ... 15 more
```

Reported by `khanh#0024` on the ArcanePlugins Discord Server. User ID: `665401740996378634`

**Comment by lokka30** [comment]
done
